language: java
jdk:
  - oraclejdk8
before_install:
  - sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base
  - sudo apt-get install -y curl libcurl4-openssl-dev libcairo-dev
  - sudo R CMD BATCH --vanilla install-r-packages.R
env:
- R_LIBS_USER="~/R"
cache:
  directories:
    - ~/R
