language: java
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base
  - wget https://cran.r-project.org/src/contrib/jsonlite_1.0.tar.gz
  - sudo R CMD INSTALL jsonlite_1.0.tar.gz