dist: bionic
language: java
notifications:
  email: false
jdk:
  - openjdk8
before_install:
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -sc)/"
  - gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
  - gpg -a --export E084DAB9 | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y r-base
  - sudo apt-get install -y curl libcurl4-openssl-dev libcairo2-dev
  - sudo R CMD BATCH --vanilla install-r-packages.R
env:
- R_LIBS_USER="~/R"
cache:
  directories:
    - ~/R
