apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadig-worker 
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-worker
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-worker
        tier: backend
    spec:
      serviceAccountName: metadig-serviceaccount
      containers:
        - name: metadig-worker
          image: docker.io/metadig/metadig-worker:dev
          #image: localhost:5000/metadig/metadig-worker:dev
          imagePullPolicy: Always

