apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: metadig-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-controller
    spec:
      serviceAccountName: metadig-serviceaccount
      containers:
      #- name: metadig-httpd
      #  image: localhost:5000/metadig/metadig-httpd:dev
      #  ports:
      #  - name: metadig-httpd
      #    containerPort: 80
      #  imagePullPolicy: Always
      - name: metadig-controller
        image: docker.io/metadig/metadig-controller:dev
        ports:
        - name: metadig-tomcat
          containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always
      #volumes:
      #- name: metadig-ctl-claim0
      #  persistentVolumeClaim:
      #    claimName: metadig-ctl-claim0

---

apiVersion: v1
kind: Service
metadata:
  name: metadig-controller
  namespace: metadig
spec:
  selector:
    app: metadig-controller
  ports:
  #- name: metadig-httpd
  #  port: 80 
  #  protocol: TCP
  #  targetPort: metadig-httpd
  - name: metadig-controller
    port: 8080
    protocol: TCP
    targetPort: metadig-tomcat
