apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: metadig
  annotations:
    # This group id has to match the group id of /data partition
    # Currently this is set to 'metadig' (1005) on docker-ucsb-4
    pv.beta.kubernetes.io/gid: "1005"
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  #persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data
    #server: 128.111.54.127
    server: docker-ucsb-4.dataone.org
    readOnly: false
