apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv 
  namespace: metadig
  annotations:
    pv.beta.kubernetes.io/gid: "1004" 
spec:
  capacity:
    storage: 245Gi 
  accessModes:
    - ReadWriteMany 
  #persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /data
    server: 128.111.54.69
    readOnly: false
