kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: metadig
  name: metadig-all
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "persistenVolues", "configMaps", "deployments", "secrets", "namespaces", "replicasets", "roles", "roleBindings", "services"]
  verbs: ["create", "get", "delete", "list", "update", "edit", "watch", "exec"]

