apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    name: busybox-pod
spec:
  containers:
  - name: busybox-pod
    image: busybox:1.29
    args: [sh, -c, 'sleep 9999999999']
    volumeMounts:
    - name: gluster-gvol0
      mountPath: /usr/share
      readOnly: false
  volumes:
  - name: gluster-gvol0
    persistentVolumeClaim:
      claimName: gluster-claim
