apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-default-volume 
  annotations:
    # Currently 'slaughter, gid=1004' owns /mnt/glusterfs
    pv.beta.kubernetes.io/gid: "1004" 
spec:
  capacity:
    storage: 250Gi 
  accessModes: 
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster 
    path: gvol0
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
