---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-cluster 
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster 
subsets:
  - addresses:
      - ip: 128.111.54.69
    ports:
      - port: 1 
  - addresses:
      - ip: 128.111.54.70
    ports:
      - port: 1 
  - addresses:
      - ip: 128.111.54.72
    ports:
      - port: 1 
