apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadig-worker 
spec:
  selector:
    matchLabels:
      app: metadig-worker
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: metadig-worker
        tier: backend
    spec:
      containers:
        - name: metadig-worker
          image: docker.io/sbpcs59/metadig-worker:dev
          imagePullPolicy: Always

