apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: metadig
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      serviceAccountName: metadig-serviceaccount
      containers:
      - name: postgres
        image: docker.io/postgres:10.4-alpine
        command: [ "su", "-", "postgres", "-c", "postgres -D /opt/local/postgresql/data" ]
        ports:
        - name: postgres
          containerPort: 5432
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: nfs-pv
          mountPath: "/opt/local"
          readOnly: false
      - name: pgbouncer
        image: edoburu/pgbouncer:1.8.1
        command: [ "/bin/sh", "-c", "pgbouncer -v /etc/pgbouncer/pgbouncer.ini" ]
        #imagePullPolicy: Always
        ports:
        - name: pgbouncer
          containerPort: 6432
        volumeMounts:
        - name: nfs-pv
          mountPath: /etc
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: nfs-pv
        persistentVolumeClaim:
          claimName: nfs-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: metadig
spec:
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  - name: pgbouncer
    port: 6432
    protocol: TCP
    targetPort: pgbouncer
