apiVersion: v1
kind: Pod
metadata:
  name: cephfs2
spec:
  containers:
  - name: cephfs-rw
    image: kubernetes/pause
    volumeMounts:
    - mountPath: "/"
      name: cephfs
  volumes:
  - name: cephfs
    cephfs:
      monitors:
      - 128.111.54.69:6789
      - 128.111.54.72:6789
      user: admin
      secretRef:
        name: ceph-secret
      #readOnly: true